### ISSUE TITLE
EMsoft make error due to EMsoftEBSDRet is not a member of sht::File

### ISSUE THREAD

**Issue by hakonanes** [EMsoft-org/SHTfile#4]
Hello!

Got this error while making EMsoft 5.0:

```bash
(base)[/home/hakon/kode/emsoft/EMsoftBuild/Release]
> cmake -DEMsoft_SDK=/home/hakon/kode/emsoft/EMsoft_SDK -DCMAKE_BUILD_TYPE=Release -S /home/hakon/kode/emsoft/EMsoft -B .
[...]
(base)[/home/hakon/kode/emsoft/EMsoftBuild/Release]
> make -j4
[  0%] Generating StringConstants files....
[  1%] Building CXX object EMsoftLib/CMakeFiles/EMsoftLib_Cpp.dir/sht_file.cpp.o
[  3%] Built target EMsoftLib_C
[  3%] Built target DIWorkflowTestPrep
/home/hakon/kode/emsoft/EMsoft/Source/EMsoftLib/sht_file.cpp: In function ‘int writeSHTfile_(char*, const char*, const char*, int32_t*, int32_t*, int32_t*, int32_t*, float*, float*, float*, int32_t*, int32_t*, double*)’:
/home/hakon/kode/emsoft/EMsoft/Source/EMsoftLib/sht_file.cpp:50:22: error: ‘EMsoftEBSDRet’ is not a member of ‘sht::File’
    return sht::File::EMsoftEBSDRet(fn, nt, doi, *sgN, *sgS, *nAt, aTy, aCd, lat, fprm, iprm, *bw, alm);
                      ^~~~~~~~~~~~~
make[2]: *** [EMsoftLib/CMakeFiles/EMsoftLib_Cpp.dir/build.make:63: EMsoftLib/CMakeFiles/EMsoftLib_Cpp.dir/sht_file.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1439: EMsoftLib/CMakeFiles/EMsoftLib_Cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target EMsoftLib_Generate_StringConstants
make: *** [Makefile:163: all] Error 2
```

Is it perhaps related to the latest commit in this repo e49ad6b9229e420f334654918f9c7b0213ffe186?

Is it possible to install EMsoft without pulling SHTfile/EMSphInx? I cannot find any such flag to set in the cmake options.

**Comment by marcdegraef** [comment]
yes,  we are working on this and ran out of time yesterday to fix it... 
it should be fixed today.  We are doing a final update/modification to 
the .sht file format today and starting this weekend everything should 
be stable again...

At the moment there is no flag to disable this part of the code but it 
is a good idea to add one...

Marc.

**Comment by hakonanes** [comment]
Thanks, that is great to hear!

**Comment by marcdegraef** [comment]
I just pushed a fix that builds on Linux CentOS7 and Mac OS X; haven't tested Windows 10 yet.  I would suggest a clean build of EMsoft...

**Comment by hakonanes** [comment]
Thanks, works on Ubuntu 19.04 as well.
